# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/.local/bin:$HOME/bin

export PATH
exec env -i HOME=$HOME TERM=$TERM PS1='\u:\w\$ ' /bin/bash
